### ISSUE TITLE
Allow to add some radio streams in my repo

### ISSUE THREAD

**Issue by Free-IPTV** [junguler/m3u-radio-music-playlists#1]
Hi @junguler,

Unlike some others, I ask beforehand.

May I transfer a few radio stations to the YZ003_Radio.m3u in my repo? Of course I give your repo as source. :-)

Greetings

Free-IPTV

**Comment by junguler** [comment]
hi, please do, i love your repo btw.

**Comment by Free-IPTV** [comment]
> 
> 
> hi, please do, i love your repo btw.

Thank you, the next updates comes tomorrow morning. :-)

**Comment by junguler** [comment]
looking forward to it.

**Comment by ArnoldSchiller** [comment]
How to add
https://jaquearnoux.de/radio
http://5.189.132.61:8000/musik.ogg
https://jaquearnoux.de/status.xsl
to your station list?

**Comment by junguler** [comment]
@ArnoldSchiller i don't understand the question, do you want me to put them in my repo or are you asking for yourself?

**Comment by junguler** [comment]
> How to add https://jaquearnoux.de/radio http://5.189.132.61:8000/musik.ogg https://jaquearnoux.de/status.xsl to your station list?

i see that you forked my repo, just make a new file and call it whatever you want and put the .m3u extension on it, copy one of the first two links on it and upload it manually to your repo

on the top of your repo, click on add file and then upload files
