### ISSUE TITLE
incomplete ---everything-full.m3u

### ISSUE THREAD

**Issue by StephanVerbeeck** [junguler/m3u-radio-music-playlists#1]
There seems to be a problem with *everything-full.m3u*

- The end of the file shows an incomplete entry, suggesting that part of the list is missing
- Many URL's have multiple headers (are these double entries, they are also in the same group)

**Comment by junguler** [comment]
hi, this repo is auto-generated from a script i've made a while back, i've tried my best to remove duplicated and broken entries as much as possible but some issues are bound to happen in an automated file generation like this.

that everything-full.m3u is just a combination of all the streams in one file, no extra work is done to it other than removing duplicated links, it's pretty much a raw file.

if you know of a way to improve the script please comment here and give me some tips to make things better, here is the script i've been running.

```
/usr/bin/aria2c -i ~/Music/list.txt -d ~/Music/bare_m3u/
for f in ~/Music/bare_m3u/*.m3u ; do mv "$f" "$(echo "$f" | sed -e 's/top_radio_//g')"; done
cat $( ls ~/Music/bare_m3u/*.m3u -v ) | awk '!seen[$0]++' > ~/Music/bare_m3u/---everything-full.m3u
cat ~/Music/bare_m3u/---everything-full.m3u | sed -n '/^#/!p' > ~/Music/bare_m3u/---everything-lite.m3u
cat ~/Music/bare_m3u/---everything-lite.m3u | shuf > ~/Music/bare_m3u/---randomized.m3u
cat ~/Music/bare_m3u/---everything-lite.m3u | sort | awk 'length>10' > ~/Music/bare_m3u/---sorted.m3u
mv ~/Music/bare_m3u/*.m3u ~/Music/m3u-radio-music-playlists
git -C ~/Music/m3u-radio-music-playlists add .
git -C ~/Music/m3u-radio-music-playlists commit -m "updating"
git -C ~/Music/m3u-radio-music-playlists push
```

**Comment by StephanVerbeeck** [comment]
Challenge accepted, does ~/Music/list.txt contain a list of *.m3u files on github or are that external URL's ?

**Comment by junguler** [comment]
they are external links from [this website](https://www.radio.pervii.com/en/online-playlists-m3u.htm)

here is the text file that i use to download the files over and over
[list.txt](https://github.com/junguler/m3u-radio-music-playlists/files/8131529/list.txt)

**Comment by junguler** [comment]
hello again, i'm going to close this issue for now, feel free to comment further or open a new issue.
