### ISSUE TITLE
Romanian is not Latin

### ISSUE THREAD

**Issue by lameventanas** [junguler/m3u-radio-music-playlists#2]
There are some Romanian stations in the Latin list.

**Comment by junguler** [comment]
hi, the decisions regarding which streams go where are not made by me, i just scrape the files from [this website](https://www.radio.pervii.com/en/online-playlists-m3u.htm) and push updates to this repo.

regardless, i'm sorry for this inconvenience but i'm simply not able to do anything about it as my knowledge of working with these kinds of things is very limited.

**Comment by junguler** [comment]
i'm going to close this issue for now, please don't hesitate to open another one if it was needed.
