### ISSUE TITLE
[radio] Incorrect name

### ISSUE THREAD

**Issue by hacketiwack** [junguler/m3u-radio-music-playlists#31]
The name of the radio should be GRRIF and not GRIFF.

https://github.com/junguler/m3u-radio-music-playlists/blob/fd906d478e3da5ce26cefe03313f1e27f6f7e625/allradio.net/French.m3u#L1216

Moreover, there is a another (better?) link to the stream:
https://grrif.ice.infomaniak.ch/grrif-128.aac

**Comment by junguler** [comment]
hello, i see, i will fix the issue the next time i push an update

keep in mind the fact that these are not named by me, i just scrape the data from the source websites and collect it here

you might want to contact the website owner/administrator as well so they can fix the issue on their end too

**Comment by junguler** [comment]
the update is coming but there was no difference in quality in both links, just different extensions of mp3 and aac, this didn't warrant a change so i left it be
