### ISSUE TITLE
Broken/Obsolete links

### ISSUE THREAD

**Issue by 4g4p3** [junguler/m3u-radio-music-playlists#37]
In the instrumental genre file, the radio "Abiding radio" is referenced with an old link.
https://github.com/junguler/m3u-radio-music-playlists/blob/d8296bbd0f751b16217302420209ad01cc550483/instrumental.m3u#L6

The current one has been changed to "https://streams.abidingradio.com:7800/1.m3u".

And, if that interests you, there are more links related to this radio at this address: https://streams.abidingradio.com:7800

**Comment by junguler** [comment]
hi, thanks for making this issue, i will fix this next time i've pushed an update

as for the address you mentioned, if there is a website that has every genre categorized i will want to scrape that (if possible) but if it's just a link that has several other suffixes to it with no way to tell which link belongs to which genre, i thinks that's more work than it's worth
