### ISSUE TITLE
Update some services please!

### ISSUE THREAD

**Issue by KevinPfeiffer** [junguler/m3u-radio-music-playlists#39]
Hello! I've recently seen that many new services are coming, but no already available service have getting updates since laut.fm. That's why I have a question to you: Could you update some services, especially zeno.fm, online_radio.eu and world-radio_map please (if possible)?

Thank you very much!

**Comment by junguler** [comment]
hello, i will absolutely update them and will start with your suggestions first, it might take a while to do as this is a side project but i will make it my priority going forward, thanks for opening this issue

**Comment by junguler** [comment]
hello, [zeno.fm](https://github.com/junguler/m3u-radio-music-playlists/tree/main/zeno.fm) folder is now updated, will do the other folders in the coming weeks

**Comment by junguler** [comment]
i will close this issue but rest assured i will continue updating the folders you've mentioned and more

**Comment by junguler** [comment]
hello again, [online_radio.eu](https://github.com/junguler/m3u-radio-music-playlists/tree/main/online_radio.eu) folder is now updated as well, will try to do the world-radio_map in the near future

**Comment by junguler** [comment]
hello again, [world-radio_map](https://github.com/junguler/m3u-radio-music-playlists/tree/main/world-radio_map) folder is now updated, i consider this issue completely resolved but i will try to slowly update other folders too

don't hesitate to open a new issue or discussion with anything else you would like, i will try to do as much as i can
